/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AutoComplete: typeof import('primevue/autocomplete')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Chip: typeof import('primevue/chip')['default']
    Column: typeof import('primevue/column')['default']
    ConvertCrypto: typeof import('./src/components/convert/ConvertCrypto.vue')['default']
    copy: typeof import('./src/components/movements/MovementTag copy.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    Header: typeof import('./src/components/header/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Loading: typeof import('./src/components/fallback/Loading.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    MovementChip: typeof import('./src/components/movements/MovementChip.vue')['default']
    MovementConvertContent: typeof import('./src/components/movements/modal/MovementConvertContent.vue')['default']
    MovementCrypto: typeof import('./src/components/movements/MovementCrypto.vue')['default']
    MovementDepositContent: typeof import('./src/components/movements/modal/MovementDepositContent.vue')['default']
    MovementModal: typeof import('./src/components/movements/modal/MovementModal.vue')['default']
    MovementStatus: typeof import('./src/components/movements/MovementStatus.vue')['default']
    MovementTag: typeof import('./src/components/movements/MovementTag.vue')['default']
    MovementWithdrawContent: typeof import('./src/components/movements/modal/MovementWithdrawContent.vue')['default']
    Password: typeof import('primevue/password')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    Rating: typeof import('primevue/rating')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScanContainer: typeof import('./src/components/scan/ScanContainer.vue')['default']
    SeveralScan: typeof import('./src/components/scan/SeveralScan.vue')['default']
    Sidebar: typeof import('./src/components/sidebar/Sidebar.vue')['default']
    Tabbar: typeof import('./src/components/tabbar/Tabbar.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    TieredMenu: typeof import('primevue/tieredmenu')['default']
    UnicScan: typeof import('./src/components/scan/UnicScan.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
  export interface GlobalDirectives {
    Ripple: typeof import('primevue/ripple')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
